import { ICategorie } from "../interface/ICategorie";

export const categorieDefaultDatas: ICategorie[] = [
  // 💸 EXPENSE
  {
    name: "Food & Groceries",
    description: "Daily meals and groceries",
    type: "EXPENSE",
    icon: "🍔",
    color: "#EF4444",
  },
  {
    name: "Transportation",
    description: "Fuel, taxi, public transport",
    type: "EXPENSE",
    icon: "🚗",
    color: "#F87171",
  },
  {
    name: "Housing",
    description: "Rent, maintenance, bills",
    type: "EXPENSE",
    icon: "🏡",
    color: "#DC2626",
  },
  {
    name: "Utilities",
    description: "Electricity, water, gas, internet",
    type: "EXPENSE",
    icon: "💡",
    color: "#FCA5A5",
  },
  {
    name: "Entertainment",
    description: "Movies, games, streaming",
    type: "EXPENSE",
    icon: "🎮",
    color: "#FB7185",
  },
  {
    name: "Health",
    description: "Medicine, insurance, doctors",
    type: "EXPENSE",
    icon: "💊",
    color: "#F43F5E",
  },
  {
    name: "Education",
    description: "Books, courses, training",
    type: "EXPENSE",
    icon: "🎓",
    color: "#E11D48",
  },
  {
    name: "Clothing",
    description: "Clothes and accessories",
    type: "EXPENSE",
    icon: "👕",
    color: "#F87171",
  },
  {
    name: "Travel",
    description: "Trips and vacations",
    type: "EXPENSE",
    icon: "✈️",
    color: "#F97316",
  },
  {
    name: "Subscriptions",
    description: "Netflix, Spotify, etc.",
    type: "EXPENSE",
    icon: "📺",
    color: "#FB923C",
  },
  {
    name: "Personal Care",
    description: "Beauty, haircuts, gym",
    type: "EXPENSE",
    icon: "💅",
    color: "#FACC15",
  },
  {
    name: "Gifts & Donations",
    description: "Charity, presents",
    type: "EXPENSE",
    icon: "🎁",
    color: "#EAB308",
  },
  {
    name: "Taxes",
    description: "Income or property taxes",
    type: "EXPENSE",
    icon: "🧾",
    color: "#FBBF24",
  },
  {
    name: "Other Expenses",
    description: "Miscellaneous expenses",
    type: "EXPENSE",
    icon: "📦",
    color: "#D97706",
  },

  // 💰 INCOME
  {
    name: "Salary",
    description: "Monthly salary or wages",
    type: "INCOME",
    icon: "💼",
    color: "#10B981",
  },
  {
    name: "Bonus",
    description: "Performance or work bonus",
    type: "INCOME",
    icon: "🎁",
    color: "#22C55E",
  },
  {
    name: "Freelance",
    description: "Income from freelance or side jobs",
    type: "INCOME",
    icon: "🧑‍💻",
    color: "#34D399",
  },
  {
    name: "Investments",
    description: "Dividends, stocks, etc.",
    type: "INCOME",
    icon: "📈",
    color: "#059669",
  },
  {
    name: "Rental Income",
    description: "Rent payments received",
    type: "INCOME",
    icon: "🏠",
    color: "#16A34A",
  },
  {
    name: "Refunds",
    description: "Tax or product refunds",
    type: "INCOME",
    icon: "💸",
    color: "#4ADE80",
  },
  {
    name: "Gift",
    description: "Money received as a gift",
    type: "INCOME",
    icon: "🎉",
    color: "#86EFAC",
  },
  {
    name: "Other Income",
    description: "Any other income source",
    type: "INCOME",
    icon: "💰",
    color: "#15803D",
  },

  // 🔄 TRANSFER
  {
    name: "Bank Transfer",
    description: "Between bank accounts",
    type: "TRANSFER",
    icon: "🏦",
    color: "#3B82F6",
  },
  {
    name: "Savings",
    description: "Money moved to savings",
    type: "TRANSFER",
    icon: "💰",
    color: "#2563EB",
  },
  {
    name: "Credit Card Payment",
    description: "Paying off credit card",
    type: "TRANSFER",
    icon: "💳",
    color: "#1D4ED8",
  },
  {
    name: "Loan Payment",
    description: "Paying back a loan",
    type: "TRANSFER",
    icon: "💵",
    color: "#1E40AF",
  },
  {
    name: "Investment Transfer",
    description: "Moving money to investments",
    type: "TRANSFER",
    icon: "📊",
    color: "#60A5FA",
  },
];
